apiVersion: v1
kind: Service
metadata:
  name: core-playground-frontend
  namespace: thinkcloudly-lab
spec:
  type: ClusterIP
  selector:
    app: core-playground-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-playground-frontend
  namespace: thinkcloudly-lab
  labels:
    app: core-playground-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-playground-frontend
  template:
    metadata:
      labels:
        app: core-playground-frontend
    spec:
      containers:
      - name: core-playground-frontend
        image: "654202376781.dkr.ecr.us-west-2.amazonaws.com/playground-frontend:latest"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: AWS_ENV_REGION
          value: us-west-2
        - name: PORT
          value: '80'
