apiVersion: v1
kind: Service
metadata:
  name: core-playground-backend
  namespace: thinkcloudly-lab
spec:
  type: ClusterIP
  selector:
    app: core-playground-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-playground-backend
  namespace: thinkcloudly-lab
  labels:
    app: core-playground-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-playground-backend
  template:
    metadata:
      labels:
        app: core-playground-backend
    spec:
      containers:
      - name: core-playground-backend
        image: "654202376781.dkr.ecr.us-west-2.amazonaws.com/playground-backend:latest"
        ports:
        - containerPort: 80
        env:
        - name: AWS_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials-mfbhfg59hc
              key: aws_id

        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-credentials-mfbhfg59hc
              key: aws_secret
        - name: AWS_ENV_REGION
          value: us-west-2
        - name: PORT
          value: '80'
        

